# Generated by Django 2.1.4 on 2018-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
