# Generated by Django 2.1.4 on 2018-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20181231_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='user_profile.Post'),
        ),
    ]
