# Generated by Django 2.1.4 on 2019-01-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190103_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
