# Generated by Django 2.1.4 on 2019-01-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
