# Generated by Django 2.1.4 on 2019-01-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
